#!/usr/bin/env bash
# Adds "Clean up temp and cache folders" to the file manager context menu.
#
# Copies the tool into ~/.local/share/temp-file-eraser and registers the menu
# entry for every file manager it finds. Nothing needs root. Safe to run again:
# it overwrites the previous installation.
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_NAME="temp-file-eraser"
DEB_NAME="temp-file-eraser-tool"

DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
INSTALL_DIR="$DATA_HOME/$PACKAGE_NAME"
PACKAGE_DIR="$INSTALL_DIR/tempfileeraser"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/$PACKAGE_NAME"

say() { printf '%s\n' "$*"; }
warn() { printf 'Warning: %s\n' "$*" >&2; }
die() { printf 'Error: %s\n' "$*" >&2; exit 1; }

# The package edition owns the same menu entries; two installs would show two
find_first() {
    local name
    for name in "$@"; do
        [[ -e "$name" ]] && { printf '%s' "$name"; return 0; }
    done
    return 1
}

if command -v dpkg-query >/dev/null 2>&1 &&
   dpkg-query -W -f='${Status}' "$DEB_NAME" 2>/dev/null | grep -q 'install ok installed'; then
    die "The package edition of $DEB_NAME is installed. Keep using it, or remove it with
       sudo apt remove $DEB_NAME
before installing the script edition."
fi

command -v python3 >/dev/null 2>&1 || die 'python3 was not found.'
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' ||
    die "python3 3.9 or newer is required (found $(python3 -V 2>&1))."
python3 -c 'import gi' 2>/dev/null ||
    die 'PyGObject was not found. Install it with: sudo apt install python3-gi'
python3 - <<'PY' 2>/dev/null || die 'GTK 4 was not found. Install it with: sudo apt install gir1.2-gtk-4.0'
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk
PY

# Repository clone: the package is in linux/, the rules at the repository root.
# Release tarball: everything sits next to this script.
SOURCE_PACKAGE="$SOURCE_DIR/tempfileeraser"
[[ -d "$SOURCE_PACKAGE" ]] || die "tempfileeraser/ was not found next to install.sh."
RULES_FILE="$(find_first "$SOURCE_DIR/rules.json" "$SOURCE_DIR/../rules/rules.json")" ||
    die 'rules.json was not found next to install.sh or in ../rules.'
VERSION_FILE="$(find_first "$SOURCE_DIR/VERSION" "$SOURCE_DIR/../VERSION")" ||
    die 'VERSION was not found next to install.sh or in ..'
INTEGRATIONS="$SOURCE_DIR/integrations"
[[ -d "$INTEGRATIONS" ]] || die "integrations/ was not found next to install.sh."

say "Installing to $INSTALL_DIR"
rm -rf "$INSTALL_DIR"
mkdir -p "$PACKAGE_DIR" "$BIN_DIR"
cp "$SOURCE_PACKAGE"/*.py "$PACKAGE_DIR/"
cp "$RULES_FILE" "$PACKAGE_DIR/rules.json"
cp "$VERSION_FILE" "$PACKAGE_DIR/VERSION"

cat > "$LAUNCHER" <<LAUNCHEOF
#!/bin/sh
# Generated by $PACKAGE_NAME install.sh
PYTHONPATH="$INSTALL_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONPATH
exec python3 -m tempfileeraser "\$@"
LAUNCHEOF
chmod +x "$LAUNCHER"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) warn "$BIN_DIR is not on your PATH. The menu entry still works, but running
         temp-file-eraser from a terminal needs a new login session." ;;
esac

# ---------------------------------------------------------------- file managers

installed_entries=()

has_nautilus_python() {
    python3 - <<'PY' >/dev/null 2>&1
import gi
for api in ('4.0', '3.0'):
    try:
        gi.require_version('Nautilus', api)
        from gi.repository import Nautilus   # noqa: F401
        raise SystemExit(0)
    except (ValueError, ImportError):
        continue
raise SystemExit(1)
PY
}

if command -v nautilus >/dev/null 2>&1; then
    if has_nautilus_python; then
        target="$DATA_HOME/nautilus-python/extensions"
        mkdir -p "$target"
        cp "$INTEGRATIONS/nautilus/temp-file-eraser-nautilus.py" "$target/"
        rm -f "$DATA_HOME/nautilus/scripts/Clean up temp and cache folders"
        installed_entries+=("Nautilus (top level of the right-click menu)")
    else
        target="$DATA_HOME/nautilus/scripts"
        mkdir -p "$target"
        cp "$INTEGRATIONS/nautilus-script/Clean up temp and cache folders" "$target/"
        chmod +x "$target/Clean up temp and cache folders"
        installed_entries+=("Nautilus (under the Scripts submenu)")
        warn "python3-nautilus is not installed, so the entry is under Scripts.
         For a top-level entry, run:
           sudo apt install python3-nautilus
         then run this installer again."
    fi
fi

if command -v nemo >/dev/null 2>&1; then
    target="$DATA_HOME/nemo/actions"
    mkdir -p "$target"
    sed "s|^Exec=temp-file-eraser|Exec=$LAUNCHER|" \
        "$INTEGRATIONS/nemo/temp-file-eraser.nemo_action" \
        > "$target/temp-file-eraser.nemo_action"
    installed_entries+=('Nemo')
fi

if command -v dolphin >/dev/null 2>&1; then
    target="$DATA_HOME/kio/servicemenus"
    mkdir -p "$target"
    sed "s|^Exec=temp-file-eraser|Exec=$LAUNCHER|" \
        "$INTEGRATIONS/kde/temp-file-eraser.desktop" > "$target/temp-file-eraser.desktop"
    chmod +x "$target/temp-file-eraser.desktop"
    installed_entries+=('Dolphin')
fi

if command -v thunar >/dev/null 2>&1; then
    if python3 "$SOURCE_DIR/integrations/thunar_action.py" --install "$CONFIG_HOME/Thunar/uca.xml" \
            "$LAUNCHER" 2>/dev/null; then
        installed_entries+=('Thunar')
    else
        warn 'Thunar was found but its custom actions file could not be updated.'
    fi
fi

# Generic "Open With" entry, with an absolute path so it works off PATH too
applications="$DATA_HOME/applications"
mkdir -p "$applications"
sed "s|^Exec=temp-file-eraser|Exec=$LAUNCHER|" \
    "$INTEGRATIONS/temp-file-eraser.desktop" > "$applications/temp-file-eraser.desktop"
command -v update-desktop-database >/dev/null 2>&1 &&
    update-desktop-database "$applications" 2>/dev/null || true

if ((${#installed_entries[@]} == 0)); then
    warn 'No supported file manager was found. The tool is installed and can be run as:
           temp-file-eraser /path/to/folder'
else
    say 'Context menu entry added for:'
    printf '  - %s\n' "${installed_entries[@]}"
fi

if pgrep -x nautilus >/dev/null 2>&1; then
    nautilus -q >/dev/null 2>&1 || true
    say 'Restarted Nautilus so it picks up the new entry.'
fi

say "Done. Right-click a folder and choose 'Clean up temp and cache folders'."
